<?php

namespace AppBundle\Repository;

/**
 * PortatilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortatilRepository extends \Doctrine\ORM\EntityRepository
{
}
